spring:
  config:
    activate:
      on-profile: test
url: jdbc:postgresql://localhost:5432/search_engine
login:  postgres
password: test
sites:
  - url: https://www.lenta.ru
    name: Лента.ру
  - url: https://www.skillbox.ru
    name: Skillbox
user-agent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"

---
spring:
  config:
    activate:
      on-profile: main
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
  datasource:
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedInserts: true
    platform: postgres
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver
sites:
  - url: https://www.lenta.ru
    name: Лента.ру
  - url: https://www.skillbox.ru
    name: Skillbox
autoScan: false
userAgent: "Chrome/100.0.4896.127"
referrer: "http://www.google.com"
timeout: 1000

