Insert into Field (Name, Selector, Weight) values ('title','title',1.0)
Insert into Field (Name, Selector, Weight) values ('body', 'body', 0.8)

Insert into Config (Id,Key,Name,Value) values (-3,'batch','batch save size (Integer)','500')
Insert into Config (Id,Key,Name,Value) values (-2,'sLiSF','saveLinksInShortFormat (boolean)','false')
Insert into Config (Id,Key,Name,Value) values (-1,'tps','Threads per Site','4')

Insert Into Parts_Of_Speech (include, Name, Short_Name) values (false,'Вводное слово','ВВОДН')

Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Глагол','Г')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Деепричастие','ДЕЕПРИЧАСТИЕ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Инфинитив','ИНФИНИТИВ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Прилагательное  [краткая форма]','КР_ПРИЛ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (false,'Междометие','МЕЖД')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (false,'Местоимение','МС')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (false,'Местоимение Принадлежащее','МС-П')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Наречие','Н')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Прилагательное','П')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Предикатив','ПРЕДК')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Предлог', 'ПРЕДЛ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Причастие','ПРИЧАСТИЕ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Существительное','С')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (false,'Союз','СОЮЗ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (false,'Частица','ЧАСТ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Числительное','ЧИСЛ')
Insert Into Parts_Of_Speech (include, Name, Short_Name) values (true,'Числительное порядковое','ЧИСЛ-П')

